/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RJTourismAPI);
  }
}(this, function(expect, RJTourismAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RJTourismAPI.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('addLike', function() {
      it('should call addLike successfully', function(done) {
        //uncomment below and update the code to test addLike
        //instance.addLike(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authenticateUser', function() {
      it('should call authenticateUser successfully', function(done) {
        //uncomment below and update the code to test authenticateUser
        //instance.authenticateUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calculateAchievement', function() {
      it('should call calculateAchievement successfully', function(done) {
        //uncomment below and update the code to test calculateAchievement
        //instance.calculateAchievement(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPost', function() {
      it('should call createPost successfully', function(done) {
        //uncomment below and update the code to test createPost
        //instance.createPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createUser', function() {
      it('should call createUser successfully', function(done) {
        //uncomment below and update the code to test createUser
        //instance.createUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteComment', function() {
      it('should call deleteComment successfully', function(done) {
        //uncomment below and update the code to test deleteComment
        //instance.deleteComment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePost', function() {
      it('should call deletePost successfully', function(done) {
        //uncomment below and update the code to test deletePost
        //instance.deletePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchLikes', function() {
      it('should call fetchLikes successfully', function(done) {
        //uncomment below and update the code to test fetchLikes
        //instance.fetchLikes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchPosts', function() {
      it('should call fetchPosts successfully', function(done) {
        //uncomment below and update the code to test fetchPosts
        //instance.fetchPosts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLike', function() {
      it('should call getLike successfully', function(done) {
        //uncomment below and update the code to test getLike
        //instance.getLike(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pingAuth', function() {
      it('should call pingAuth successfully', function(done) {
        //uncomment below and update the code to test pingAuth
        //instance.pingAuth(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
