/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthResponse from './model/AuthResponse';
import CalculateAchievementResponse from './model/CalculateAchievementResponse';
import CreatePostRequest from './model/CreatePostRequest';
import FetchLikesResponse from './model/FetchLikesResponse';
import FetchPostsResponse from './model/FetchPostsResponse';
import GetLikeResponse from './model/GetLikeResponse';
import LikeRequest from './model/LikeRequest';
import PostDTO from './model/PostDTO';
import UserCredentials from './model/UserCredentials';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RJTourismAPI = require('index'); // See note below*.
* var xxxSvc = new RJTourismAPI.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RJTourismAPI.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RJTourismAPI.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RJTourismAPI.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthResponse model constructor.
     * @property {module:model/AuthResponse}
     */
    AuthResponse,

    /**
     * The CalculateAchievementResponse model constructor.
     * @property {module:model/CalculateAchievementResponse}
     */
    CalculateAchievementResponse,

    /**
     * The CreatePostRequest model constructor.
     * @property {module:model/CreatePostRequest}
     */
    CreatePostRequest,

    /**
     * The FetchLikesResponse model constructor.
     * @property {module:model/FetchLikesResponse}
     */
    FetchLikesResponse,

    /**
     * The FetchPostsResponse model constructor.
     * @property {module:model/FetchPostsResponse}
     */
    FetchPostsResponse,

    /**
     * The GetLikeResponse model constructor.
     * @property {module:model/GetLikeResponse}
     */
    GetLikeResponse,

    /**
     * The LikeRequest model constructor.
     * @property {module:model/LikeRequest}
     */
    LikeRequest,

    /**
     * The PostDTO model constructor.
     * @property {module:model/PostDTO}
     */
    PostDTO,

    /**
     * The UserCredentials model constructor.
     * @property {module:model/UserCredentials}
     */
    UserCredentials,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
