/**
 * ApiController.js
 * 
 * This file defines the ApiController class, which serves as a wrapper around the API client generated by OpenAPI.
 * It provides methods to interact with the backend API, such as fetching posts, creating new posts, etc.
 */
import UserCredentials from '../api/src/model/UserCredentials';
import LikeRequest from '../api/src/model/LikeRequest';
import { Api } from './ApiInstance';  // Import the configured instance, not the class

export default class ApiController {

  constructor() {
    this.api = Api;
  }

  /**
   * Fetch all posts
   * @returns {Promise<Array>}
   */
  async fetchPosts() { 
    try {
      const response = await this.api.fetchPosts();
      console.log(response)
      return response.posts || [];  // Return empty array if no posts
    } catch (error) {
      console.error('Failed to fetch posts:', error);
      throw error;
    }
  }

  async getLikesForPost(postId) {
    try {
      const response = await this.api.fetchLikes(postId);
      return response.likeCount || 0;  // Return 0 if no likes
    } catch (error) {
      console.error('Failed to fetch likes for post:', postId, error);
      throw error;
    }
  }

  async fetchPostsByCategory(catId){
    try {
      const response = await this.api.fetchPostsByCategory(catId);
      console.log(response)
      return response.posts || [];  // Return empty array if no posts
    } catch (error) {
      console.error('Failed to fetch posts:', error);
      throw error;
    }
  }

  async authenticateUser(username, password) {
    const request = new UserCredentials(password, username, false)
    try {
      await this.api.authenticateUser({ userCredentials: request })
      return true // success if no error thrown
    } catch (error) {
      console.error('Failed to authenticate user:', error)
      throw error
    }
  }

  async createUser(username, password){
    const request = new UserCredentials(password, username, false)
    try{
      await this.api.createUser({ userCredentials: request })
      return true
    } catch (error){
      console.error('Failed to create new user')
      throw error
    }
  }

  async calculateAchievements(username) {
    try {
      const response = await this.api.calculateAchievement(username)
      return response
    } catch (error) {
      console.error('Failed to calculate achievements:', error)
      throw error
    }
  }

  async createPost(username, categoryId, title, description, address) {
    try {
      const response = await this.api.createPost({
        createPostRequest: {
          username,
          categoryId,
          title,
          description,
          address,
          datePosted: new Date().toISOString()
        }
      })
      return response
    } catch (error) {
      console.error('Failed to create post:', error)
      throw error
    }
  }

  async addLike(username, postId, likeStatus){
    try {
      const request = new LikeRequest(username, postId)
      request.setStatus(likeStatus)
      await this.api.addLike({ likeRequest: request })
    } catch (error) {
      console.error('Failed to add like: ', error);
      throw error
    }
  }

  async getLike(username, postId) {
    try {
      const request = new LikeRequest(username, postId)
      console.log('getLike request:', request.getUsername(), request.getPostId())
      const response = await this.api.getLike( {likeRequest: request} )
      return response
    } catch (error) {
      if (error.status === 404) {
        return null
      }
      console.error('Failed to get like:', error)
      throw error
    }
  }

  async checkIsAdmin(username) {
    try {
      await this.api.isAdmin(username)
      return true
    } catch (error) {
      if (error.status === 401) {
        return false
      }
      throw error
    }
  }

  async deletePost(postId) {
    try {
      await this.api.deletePost(postId)
      return true
    } catch (error) {
      console.error('Failed to delete post:', error)
      throw error
    }
  }
}