/**
 * ApiController.js
 * 
 * This file defines the ApiController class, which serves as a wrapper around the API client generated by OpenAPI.
 * It provides methods to interact with the backend API, such as fetching posts, creating new posts, etc.
 */
import { Api } from './ApiInstance';  // Import the configured instance, not the class

export default class ApiController {

  constructor() {
    this.api = Api;
  }

  /**
   * Fetch all posts
   * @returns {Promise<Array>}
   */
  async fetchPosts() { 
    try {
      const response = await this.api.fetchPosts();
      console.log(response)
      return response.posts || [];  // Return empty array if no posts
    } catch (error) {
      console.error('Failed to fetch posts:', error);
      throw error;
    }
  }

  async getLikesForPost(postId) {
    try {
      const response = await this.api.fetchLikes(postId);
      return response.likeCount || 0;  // Return 0 if no likes
    } catch (error) {
      console.error('Failed to fetch likes for post:', postId, error);
      throw error;
    }
  }
}