/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CalculateAchievementResponse from '../model/CalculateAchievementResponse';
import CategoryResponse from '../model/CategoryResponse';
import CreatePostRequest from '../model/CreatePostRequest';
import FetchLikesResponse from '../model/FetchLikesResponse';
import FetchPostsResponse from '../model/FetchPostsResponse';
import GetLikeResponse from '../model/GetLikeResponse';
import LikeRequest from '../model/LikeRequest';
import UserCredentials from '../model/UserCredentials';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Add a like to a post with a given user ID and post ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/LikeRequest} [likeRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    addLikeWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['likeRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/content/add-like', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Add a like to a post with a given user ID and post ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/LikeRequest} opts.likeRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    addLike(opts) {
      return this.addLikeWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * For a given username and password, authenticate them.
     * @param {Object} opts Optional parameters
     * @param {module:model/UserCredentials} [userCredentials] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    authenticateUserWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['userCredentials'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/authentication/authenticate-user', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * For a given username and password, authenticate them.
     * @param {Object} opts Optional parameters
     * @param {module:model/UserCredentials} opts.userCredentials 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    authenticateUser(opts) {
      return this.authenticateUserWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Calculate the achievements for a given user ID.
     * @param {Number} userId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CalculateAchievementResponse} and HTTP response
     */
    calculateAchievementWithHttpInfo(userId) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling calculateAchievement");
      }

      let pathParams = {
        'userId': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CalculateAchievementResponse;
      return this.apiClient.callApi(
        '/v1/account/calculate-achievement/{userId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Calculate the achievements for a given user ID.
     * @param {Number} userId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CalculateAchievementResponse}
     */
    calculateAchievement(userId) {
      return this.calculateAchievementWithHttpInfo(userId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a post with a given title and content.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreatePostRequest} [createPostRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    createPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['createPostRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/content/create-post', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a post with a given title and content.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreatePostRequest} opts.createPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    createPost(opts) {
      return this.createPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a user account with a given username and password.
     * @param {Object} opts Optional parameters
     * @param {module:model/UserCredentials} [userCredentials] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    createUserWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['userCredentials'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/account/create-user', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a user account with a given username and password.
     * @param {Object} opts Optional parameters
     * @param {module:model/UserCredentials} opts.userCredentials 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    createUser(opts) {
      return this.createUserWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a comment with a given comment ID.
     * @param {Number} commentId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteCommentWithHttpInfo(commentId) {
      let postBody = null;
      // verify the required parameter 'commentId' is set
      if (commentId === undefined || commentId === null) {
        throw new Error("Missing the required parameter 'commentId' when calling deleteComment");
      }

      let pathParams = {
        'commentId': commentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/content/delete-comment/{commentId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a comment with a given comment ID.
     * @param {Number} commentId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteComment(commentId) {
      return this.deleteCommentWithHttpInfo(commentId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a post with a given post ID.
     * @param {Number} postId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deletePostWithHttpInfo(postId) {
      let postBody = null;
      // verify the required parameter 'postId' is set
      if (postId === undefined || postId === null) {
        throw new Error("Missing the required parameter 'postId' when calling deletePost");
      }

      let pathParams = {
        'postId': postId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/content/delete-post/{postId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a post with a given post ID.
     * @param {Number} postId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deletePost(postId) {
      return this.deletePostWithHttpInfo(postId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch the number of likes for a given post ID.
     * @param {Number} postId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/FetchLikesResponse} and HTTP response
     */
    fetchLikesWithHttpInfo(postId) {
      let postBody = null;
      // verify the required parameter 'postId' is set
      if (postId === undefined || postId === null) {
        throw new Error("Missing the required parameter 'postId' when calling fetchLikes");
      }

      let pathParams = {
        'postId': postId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = FetchLikesResponse;
      return this.apiClient.callApi(
        '/v1/content/fetch-likes/{postId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Fetch the number of likes for a given post ID.
     * @param {Number} postId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/FetchLikesResponse}
     */
    fetchLikes(postId) {
      return this.fetchLikesWithHttpInfo(postId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch all posts.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/FetchPostsResponse} and HTTP response
     */
    fetchPostsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = FetchPostsResponse;
      return this.apiClient.callApi(
        '/v1/content/fetch-posts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Fetch all posts.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/FetchPostsResponse}
     */
    fetchPosts() {
      return this.fetchPostsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fetch posts by a given category id.
     * @param {Number} catId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/FetchPostsResponse} and HTTP response
     */
    fetchPostsByCategoryWithHttpInfo(catId) {
      let postBody = null;
      // verify the required parameter 'catId' is set
      if (catId === undefined || catId === null) {
        throw new Error("Missing the required parameter 'catId' when calling fetchPostsByCategory");
      }

      let pathParams = {
        'catId': catId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = FetchPostsResponse;
      return this.apiClient.callApi(
        '/v1/content/fetch-posts-by-category/{catId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Fetch posts by a given category id.
     * @param {Number} catId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/FetchPostsResponse}
     */
    fetchPostsByCategory(catId) {
      return this.fetchPostsByCategoryWithHttpInfo(catId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get the associated category name for an id.
     * @param {Number} catId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CategoryResponse} and HTTP response
     */
    getCategoryWithHttpInfo(catId) {
      let postBody = null;
      // verify the required parameter 'catId' is set
      if (catId === undefined || catId === null) {
        throw new Error("Missing the required parameter 'catId' when calling getCategory");
      }

      let pathParams = {
        'catId': catId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CategoryResponse;
      return this.apiClient.callApi(
        '/v1/content/get-category/{catId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get the associated category name for an id.
     * @param {Number} catId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CategoryResponse}
     */
    getCategory(catId) {
      return this.getCategoryWithHttpInfo(catId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get the like status for a given user ID and post ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/LikeRequest} [likeRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetLikeResponse} and HTTP response
     */
    getLikeWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['likeRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GetLikeResponse;
      return this.apiClient.callApi(
        '/v1/content/get-like', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get the like status for a given user ID and post ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/LikeRequest} opts.likeRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetLikeResponse}
     */
    getLike(opts) {
      return this.getLikeWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Ping authentication controller to see if it is reachable
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    pingAuthWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/authentication', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Ping authentication controller to see if it is reachable
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    pingAuth() {
      return this.pingAuthWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
