/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthResponse model module.
 * @module model/AuthResponse
 * @version 1.0.0
 */
class AuthResponse {
    /**
     * Constructs a new <code>AuthResponse</code>.
     * @alias module:model/AuthResponse
     */
    constructor() { 
        
        AuthResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthResponse} obj Optional instance to populate.
     * @return {module:model/AuthResponse} The populated <code>AuthResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthResponse();

            if (data.hasOwnProperty('resp')) {
                obj['resp'] = ApiClient.convertToType(data['resp'], 'Number');
            }
            if (data.hasOwnProperty('authSuccess')) {
                obj['authSuccess'] = ApiClient.convertToType(data['authSuccess'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }

/**
     * @return {Number}
     */
    getResp() {
        return this.resp;
    }

    /**
     * @param {Number} resp
     */
    setResp(resp) {
        this['resp'] = resp;
    }
/**
     * @return {Boolean}
     */
    getAuthSuccess() {
        return this.authSuccess;
    }

    /**
     * @param {Boolean} authSuccess
     */
    setAuthSuccess(authSuccess) {
        this['authSuccess'] = authSuccess;
    }

}



/**
 * @member {Number} resp
 */
AuthResponse.prototype['resp'] = undefined;

/**
 * @member {Boolean} authSuccess
 */
AuthResponse.prototype['authSuccess'] = undefined;






export default AuthResponse;

