/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CategoryResponse model module.
 * @module model/CategoryResponse
 * @version 1.0.0
 */
class CategoryResponse {
    /**
     * Constructs a new <code>CategoryResponse</code>.
     * @alias module:model/CategoryResponse
     */
    constructor() { 
        
        CategoryResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CategoryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategoryResponse} obj Optional instance to populate.
     * @return {module:model/CategoryResponse} The populated <code>CategoryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryResponse();

            if (data.hasOwnProperty('categoryName')) {
                obj['categoryName'] = ApiClient.convertToType(data['categoryName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CategoryResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CategoryResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['categoryName'] && !(typeof data['categoryName'] === 'string' || data['categoryName'] instanceof String)) {
            throw new Error("Expected the field `categoryName` to be a primitive type in the JSON string but got " + data['categoryName']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getCategoryName() {
        return this.categoryName;
    }

    /**
     * @param {String} categoryName
     */
    setCategoryName(categoryName) {
        this['categoryName'] = categoryName;
    }

}



/**
 * @member {String} categoryName
 */
CategoryResponse.prototype['categoryName'] = undefined;






export default CategoryResponse;

