/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreatePostRequest model module.
 * @module model/CreatePostRequest
 * @version 1.0.0
 */
class CreatePostRequest {
    /**
     * Constructs a new <code>CreatePostRequest</code>.
     * @alias module:model/CreatePostRequest
     */
    constructor() { 
        
        CreatePostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreatePostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePostRequest} obj Optional instance to populate.
     * @return {module:model/CreatePostRequest} The populated <code>CreatePostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePostRequest();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('categoryId')) {
                obj['categoryId'] = ApiClient.convertToType(data['categoryId'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('datePosted')) {
                obj['datePosted'] = ApiClient.convertToType(data['datePosted'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreatePostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreatePostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getUsername() {
        return this.username;
    }

    /**
     * @param {String} username
     */
    setUsername(username) {
        this['username'] = username;
    }
/**
     * @return {Number}
     */
    getCategoryId() {
        return this.categoryId;
    }

    /**
     * @param {Number} categoryId
     */
    setCategoryId(categoryId) {
        this['categoryId'] = categoryId;
    }
/**
     * @return {String}
     */
    getTitle() {
        return this.title;
    }

    /**
     * @param {String} title
     */
    setTitle(title) {
        this['title'] = title;
    }
/**
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * @param {String} description
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * @return {String}
     */
    getAddress() {
        return this.address;
    }

    /**
     * @param {String} address
     */
    setAddress(address) {
        this['address'] = address;
    }
/**
     * @return {Date}
     */
    getDatePosted() {
        return this.datePosted;
    }

    /**
     * @param {Date} datePosted
     */
    setDatePosted(datePosted) {
        this['datePosted'] = datePosted;
    }

}



/**
 * @member {String} username
 */
CreatePostRequest.prototype['username'] = undefined;

/**
 * @member {Number} categoryId
 */
CreatePostRequest.prototype['categoryId'] = undefined;

/**
 * @member {String} title
 */
CreatePostRequest.prototype['title'] = undefined;

/**
 * @member {String} description
 */
CreatePostRequest.prototype['description'] = undefined;

/**
 * @member {String} address
 */
CreatePostRequest.prototype['address'] = undefined;

/**
 * @member {Date} datePosted
 */
CreatePostRequest.prototype['datePosted'] = undefined;






export default CreatePostRequest;

