/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FetchLikesResponse model module.
 * @module model/FetchLikesResponse
 * @version 1.0.0
 */
class FetchLikesResponse {
    /**
     * Constructs a new <code>FetchLikesResponse</code>.
     * @alias module:model/FetchLikesResponse
     */
    constructor() { 
        
        FetchLikesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FetchLikesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FetchLikesResponse} obj Optional instance to populate.
     * @return {module:model/FetchLikesResponse} The populated <code>FetchLikesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FetchLikesResponse();

            if (data.hasOwnProperty('likeCount')) {
                obj['likeCount'] = ApiClient.convertToType(data['likeCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FetchLikesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FetchLikesResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }

/**
     * @return {Number}
     */
    getLikeCount() {
        return this.likeCount;
    }

    /**
     * @param {Number} likeCount
     */
    setLikeCount(likeCount) {
        this['likeCount'] = likeCount;
    }

}



/**
 * @member {Number} likeCount
 */
FetchLikesResponse.prototype['likeCount'] = undefined;






export default FetchLikesResponse;

