/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostDTO from './PostDTO';

/**
 * The FetchPostsResponse model module.
 * @module model/FetchPostsResponse
 * @version 1.0.0
 */
class FetchPostsResponse {
    /**
     * Constructs a new <code>FetchPostsResponse</code>.
     * @alias module:model/FetchPostsResponse
     */
    constructor() { 
        
        FetchPostsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FetchPostsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FetchPostsResponse} obj Optional instance to populate.
     * @return {module:model/FetchPostsResponse} The populated <code>FetchPostsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FetchPostsResponse();

            if (data.hasOwnProperty('posts')) {
                obj['posts'] = ApiClient.convertToType(data['posts'], [PostDTO]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FetchPostsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FetchPostsResponse</code>.
     */
    static validateJSON(data) {
        if (data['posts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['posts'])) {
                throw new Error("Expected the field `posts` to be an array in the JSON data but got " + data['posts']);
            }
            // validate the optional field `posts` (array)
            for (const item of data['posts']) {
                PostDTO.validateJSON(item);
            };
        }

        return true;
    }

/**
     * @return {Array.<module:model/PostDTO>}
     */
    getPosts() {
        return this.posts;
    }

    /**
     * @param {Array.<module:model/PostDTO>} posts
     */
    setPosts(posts) {
        this['posts'] = posts;
    }

}



/**
 * @member {Array.<module:model/PostDTO>} posts
 */
FetchPostsResponse.prototype['posts'] = undefined;






export default FetchPostsResponse;

