/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LikeRequest model module.
 * @module model/LikeRequest
 * @version 1.0.0
 */
class LikeRequest {
    /**
     * Constructs a new <code>LikeRequest</code>.
     * @alias module:model/LikeRequest
     * @param userId {Number} 
     * @param postId {Number} 
     */
    constructor(userId, postId) { 
        
        LikeRequest.initialize(this, userId, postId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, postId) { 
        obj['userId'] = userId;
        obj['postId'] = postId;
    }

    /**
     * Constructs a <code>LikeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LikeRequest} obj Optional instance to populate.
     * @return {module:model/LikeRequest} The populated <code>LikeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LikeRequest();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('postId')) {
                obj['postId'] = ApiClient.convertToType(data['postId'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LikeRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LikeRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LikeRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

/**
     * @return {Number}
     */
    getUserId() {
        return this.userId;
    }

    /**
     * @param {Number} userId
     */
    setUserId(userId) {
        this['userId'] = userId;
    }
/**
     * @return {Number}
     */
    getPostId() {
        return this.postId;
    }

    /**
     * @param {Number} postId
     */
    setPostId(postId) {
        this['postId'] = postId;
    }
/**
     * @return {Boolean}
     */
    getStatus() {
        return this.status;
    }

    /**
     * @param {Boolean} status
     */
    setStatus(status) {
        this['status'] = status;
    }

}

LikeRequest.RequiredProperties = ["userId", "postId"];

/**
 * @member {Number} userId
 */
LikeRequest.prototype['userId'] = undefined;

/**
 * @member {Number} postId
 */
LikeRequest.prototype['postId'] = undefined;

/**
 * @member {Boolean} status
 */
LikeRequest.prototype['status'] = undefined;






export default LikeRequest;

