/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserCredentials model module.
 * @module model/UserCredentials
 * @version 1.0.0
 */
class UserCredentials {
    /**
     * Constructs a new <code>UserCredentials</code>.
     * @alias module:model/UserCredentials
     * @param hashedPassword {String} 
     * @param username {String} 
     * @param isAdmin {Boolean} 
     */
    constructor(hashedPassword, username, isAdmin) { 
        
        UserCredentials.initialize(this, hashedPassword, username, isAdmin);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hashedPassword, username, isAdmin) { 
        obj['hashedPassword'] = hashedPassword;
        obj['username'] = username;
        obj['isAdmin'] = isAdmin;
    }

    /**
     * Constructs a <code>UserCredentials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserCredentials} obj Optional instance to populate.
     * @return {module:model/UserCredentials} The populated <code>UserCredentials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserCredentials();

            if (data.hasOwnProperty('hashedPassword')) {
                obj['hashedPassword'] = ApiClient.convertToType(data['hashedPassword'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('isAdmin')) {
                obj['isAdmin'] = ApiClient.convertToType(data['isAdmin'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserCredentials</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserCredentials</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserCredentials.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['hashedPassword'] && !(typeof data['hashedPassword'] === 'string' || data['hashedPassword'] instanceof String)) {
            throw new Error("Expected the field `hashedPassword` to be a primitive type in the JSON string but got " + data['hashedPassword']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getHashedPassword() {
        return this.hashedPassword;
    }

    /**
     * @param {String} hashedPassword
     */
    setHashedPassword(hashedPassword) {
        this['hashedPassword'] = hashedPassword;
    }
/**
     * @return {String}
     */
    getUsername() {
        return this.username;
    }

    /**
     * @param {String} username
     */
    setUsername(username) {
        this['username'] = username;
    }
/**
     * @return {Boolean}
     */
    getIsAdmin() {
        return this.isAdmin;
    }

    /**
     * @param {Boolean} isAdmin
     */
    setIsAdmin(isAdmin) {
        this['isAdmin'] = isAdmin;
    }

}

UserCredentials.RequiredProperties = ["hashedPassword", "username", "isAdmin"];

/**
 * @member {String} hashedPassword
 */
UserCredentials.prototype['hashedPassword'] = undefined;

/**
 * @member {String} username
 */
UserCredentials.prototype['username'] = undefined;

/**
 * @member {Boolean} isAdmin
 */
UserCredentials.prototype['isAdmin'] = undefined;






export default UserCredentials;

