spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5332/rjtourism
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

#drop/reset database on each app startup
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true