/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.rjtoursim.api.controller;

import com.rjtoursim.api.model.UserCredentials;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-09T23:05:07.263961610Z[Europe/London]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "v1", description = "the v1 API")
public interface V1Api {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /v1/authentication/authenticate-user : For a given username and password, authenticate them.
     *
     * @param userCredentials  (optional)
     * @return Authenitcation successfull (status code 200)
     *         or Unauthorized - Invalid username or password (status code 401)
     *         or Internal Server Error - Something went wrong on the server side (status code 500)
     */
    @Operation(
        operationId = "authenticateUser",
        summary = "For a given username and password, authenticate them.",
        responses = {
            @ApiResponse(responseCode = "200", description = "Authenitcation successfull"),
            @ApiResponse(responseCode = "401", description = "Unauthorized - Invalid username or password"),
            @ApiResponse(responseCode = "500", description = "Internal Server Error - Something went wrong on the server side")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/authentication/authenticate-user",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> _authenticateUser(
        @Parameter(name = "UserCredentials", description = "") @Valid @RequestBody(required = false) UserCredentials userCredentials
    ) {
        return authenticateUser(userCredentials);
    }

    // Override this method
    default  ResponseEntity<Void> authenticateUser(UserCredentials userCredentials) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /v1/account/create-user : Create a user account with a given username and password.
     *
     * @param userCredentials  (optional)
     * @return Created (status code 201)
     *         or Conflict - Username already exists (status code 409)
     */
    @Operation(
        operationId = "createUser",
        summary = "Create a user account with a given username and password.",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "409", description = "Conflict - Username already exists")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/account/create-user",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> _createUser(
        @Parameter(name = "UserCredentials", description = "") @Valid @RequestBody(required = false) UserCredentials userCredentials
    ) {
        return createUser(userCredentials);
    }

    // Override this method
    default  ResponseEntity<Void> createUser(UserCredentials userCredentials) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /v1/authentication : Ping authentication controller to see if it is reachable
     *
     * @return Pinged successfully (status code 200)
     */
    @Operation(
        operationId = "pingAuth",
        summary = "Ping authentication controller to see if it is reachable",
        responses = {
            @ApiResponse(responseCode = "200", description = "Pinged successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/authentication"
    )
    
    default ResponseEntity<Void> _pingAuth(
        
    ) {
        return pingAuth();
    }

    // Override this method
    default  ResponseEntity<Void> pingAuth() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
